# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/mubu.har

"""
1.替换base_url
2.设置folderid为变量
3.设置host为全部变量




"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin1(HttpRunner):

    config = Config("testcase description").verify(False).base_url("https://mubu.com")\
        .variables(**{
        "host": "mubu.com",
        # "phone": "19945635122",
        # "password": "123456"
    })

    teststeps = [
        Step(
            RunRequest("/")
            .get("/")
            .with_headers(
                **{
                    "pragma": "no-cache",
                    "cache-control": "no-cache",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "reg_prepareId": "17393731f1f-17393731f1c-40b7-b9d7-23b09b8887ba",
                    "reg_focusId": "4d9675b1-742c-40b7-b9d7-17393732391",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "SLARDAR_WEB_ID": "faf1cb34-3f5b-4c2a-a37d-be663e70a152",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906710",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/asset/dep/icomoon/fonts/icomoon.ttf")
            .get("/asset/dep/icomoon/fonts/icomoon.ttf")
            .with_params(**{"69gcwh": ""})
            .with_headers(
                **{
                    "pragma": "no-cache",
                    "cache-control": "no-cache",
                    "origin": "https://${host}",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "*/*",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "font",
                    "referer": "https://${host}/asset/dep/icomoon/style-ba43dd96a4.css",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "reg_prepareId": "17393731f1f-17393731f1c-40b7-b9d7-23b09b8887ba",
                    "reg_focusId": "4d9675b1-742c-40b7-b9d7-17393732391",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "SLARDAR_WEB_ID": "faf1cb34-3f5b-4c2a-a37d-be663e70a152",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906710",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
            .get("/login")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "reg_prepareId": "17393731f1f-17393731f1c-40b7-b9d7-23b09b8887ba",
                    "reg_focusId": "4d9675b1-742c-40b7-b9d7-17393732391",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906761",
                    "SLARDAR_WEB_ID": "f7aac6d5-e6c6-4743-ad5e-ff2e30ba4d70",
                    "_gat": "1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("/login/password")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "4897ae66-a54b-49f8-9e08-002d14f43a2d",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906765",
                    "reg_prepareId": "1739374b32b-1739374b1df-4209-8de4-5623503e8dcd",
                    "reg_focusId": "740e5278-85da-4209-8de4-1739374b858",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("/api/login/submit")
            .with_headers(
                **{
                    "content-length": "47",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "_gat": "1",
                    "reg_prepareId": "1739374b32b-1739374b1df-4209-8de4-5623503e8dcd",
                    "reg_focusId": "740e5278-85da-4209-8de4-1739374b858",
                    "SLARDAR_WEB_ID": "7652cb12-1b80-45e1-a0af-e0120e62087a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906767",
                }
            )
            .with_data(
                {"phone": "${phone}", "password": "${password}", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/list")
            .get("/list")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "_gat": "1",
                    "reg_prepareId": "1739374b32b-1739374b1df-4209-8de4-5623503e8dcd",
                    "reg_focusId": "740e5278-85da-4209-8de4-1739374b858",
                    "SLARDAR_WEB_ID": "7652cb12-1b80-45e1-a0af-e0120e62087a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906767",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQ5ODc2OSwiaWF0IjoxNTk1OTA2NzY5fQ.0KBJhXbDqlhs4qStaimpTETKKwgEI-XZJiUz5qN3zxLHt82fq6O9ULWFR_wg21LSIht5Qq2yN9gcFz1QMlc7rw",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("/api/list/tip_new_update")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "_gat": "1",
                    "reg_prepareId": "1739374b32b-1739374b1df-4209-8de4-5623503e8dcd",
                    "reg_focusId": "740e5278-85da-4209-8de4-1739374b858",
                    "SLARDAR_WEB_ID": "7652cb12-1b80-45e1-a0af-e0120e62087a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906767",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQ5ODc2OSwiaWF0IjoxNTk1OTA2NzY5fQ.0KBJhXbDqlhs4qStaimpTETKKwgEI-XZJiUz5qN3zxLHt82fq6O9ULWFR_wg21LSIht5Qq2yN9gcFz1QMlc7rw",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("/api/list/get")
            .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "_gat": "1",
                    "reg_prepareId": "1739374b32b-1739374b1df-4209-8de4-5623503e8dcd",
                    "reg_focusId": "740e5278-85da-4209-8de4-1739374b858",
                    "SLARDAR_WEB_ID": "7652cb12-1b80-45e1-a0af-e0120e62087a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906767",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQ5ODc2OSwiaWF0IjoxNTk1OTA2NzY5fQ.0KBJhXbDqlhs4qStaimpTETKKwgEI-XZJiUz5qN3zxLHt82fq6O9ULWFR_wg21LSIht5Qq2yN9gcFz1QMlc7rw",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
            .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "x-requested-with": "XMLHttpRequest",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "_gat": "1",
                    "reg_prepareId": "1739374b32b-1739374b1df-4209-8de4-5623503e8dcd",
                    "reg_focusId": "740e5278-85da-4209-8de4-1739374b858",
                    "SLARDAR_WEB_ID": "7652cb12-1b80-45e1-a0af-e0120e62087a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906767",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQ5ODc2OSwiaWF0IjoxNTk1OTA2NzY5fQ.0KBJhXbDqlhs4qStaimpTETKKwgEI-XZJiUz5qN3zxLHt82fq6O9ULWFR_wg21LSIht5Qq2yN9gcFz1QMlc7rw",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),

    ]


if __name__ == "__main__":
    TestCaseMubuLogin1().test_start()
