# NOTE: Generated By HttpRunner v3.1.3
# FROM: har/mubu.har

"""
1.替换base_url
2.设置folderid为变量
3.设置host为全部变量




"""

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from httprunner_homework.demo.testcases.mubu_login1_test import TestCaseMubuLogin1 as MubuLogin1


class TestCaseMubuCreateFolder(HttpRunner):

    config = Config("create folder").verify(False).base_url("https://mubu.com")\
        .variables(**{
        "host": "mubu.com",
        "name": "testaa"

    })

    teststeps = [
        Step(
            RunTestCase("login mubu").with_variables(phone="19945635122", password="123456").call(MubuLogin1)
        ),
        Step(
            RunRequest("/api/list/create_folder")
            .post("/api/list/create_folder")
            .with_headers(
                **{
                    "content-length": "19",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "_gat": "1",
                    "reg_prepareId": "1739374b32b-1739374b1df-4209-8de4-5623503e8dcd",
                    "reg_focusId": "740e5278-85da-4209-8de4-1739374b858",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQ5ODc2OSwiaWF0IjoxNTk1OTA2NzY5fQ.0KBJhXbDqlhs4qStaimpTETKKwgEI-XZJiUz5qN3zxLHt82fq6O9ULWFR_wg21LSIht5Qq2yN9gcFz1QMlc7rw",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                    "SLARDAR_WEB_ID": "d5f06cee-dfa5-4c80-a348-16f4d73c31b9",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906770",
                }
            )
            .with_data({"folderId": "0", "name": "123"})
            .extract()
            .with_jmespath("body.data.folder.id", "id")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("/api/list/get")
            .with_headers(
                **{
                    "content-length": "38",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "_gat": "1",
                    "reg_prepareId": "1739374b32b-1739374b1df-4209-8de4-5623503e8dcd",
                    "reg_focusId": "740e5278-85da-4209-8de4-1739374b858",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQ5ODc2OSwiaWF0IjoxNTk1OTA2NzY5fQ.0KBJhXbDqlhs4qStaimpTETKKwgEI-XZJiUz5qN3zxLHt82fq6O9ULWFR_wg21LSIht5Qq2yN9gcFz1QMlc7rw",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                    "SLARDAR_WEB_ID": "d5f06cee-dfa5-4c80-a348-16f4d73c31b9",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906770",
                }
            )
            .with_data({"folderId": "${id}", "sort": "time", "keywords": "", "source": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/rename_folder")
            .post("/api/list/rename_folder")
            .with_headers(
                **{
                    "content-length": "30",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "HttpRunner/${get_httprunner_version()}",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/list",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.1509225228.1595645061",
                    "data_unique_id": "c4c1aa63-cc8a-40c1-bd5e-368b7c69464e",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1595654108",
                    "mubu_inner": "1",
                    "s_v_web_id": "kd17h9te_kcbr4MS4_S8N8_48iv_8agO_teIOtEdLmFsT",
                    "_gid": "GA1.2.2055068782.1595832349",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "language": "en-US",
                    "country": "US",
                    "csrf_token": "94e49016-4621-4448-a532-95dcb2e9bddf",
                    "data-unique-id": "d24e3200-d081-11ea-9252-f7817986a46e",
                    "SESSION": "6a7c1ca4-2d68-4661-aaef-1b5bb60cde4e",
                    "_gat": "1",
                    "reg_prepareId": "1739374b32b-1739374b1df-4209-8de4-5623503e8dcd",
                    "reg_focusId": "740e5278-85da-4209-8de4-1739374b858",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODM2MjY1OCIsImV4cCI6MTU5ODQ5ODc2OSwiaWF0IjoxNTk1OTA2NzY5fQ.0KBJhXbDqlhs4qStaimpTETKKwgEI-XZJiUz5qN3zxLHt82fq6O9ULWFR_wg21LSIht5Qq2yN9gcFz1QMlc7rw",
                    "user_persistence": "e28a89d6-2288-4247-af6f-d8ac334c870f",
                    "SLARDAR_WEB_ID": "d5f06cee-dfa5-4c80-a348-16f4d73c31b9",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1595906770",
                }
            )
            .with_data({"folderId": "${id}", "name": "${name}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal("body.data", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreateFolder().test_start()
